receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 1
    sampling_thereafter: 1

extensions:
  health_check:

service:
  pipelines:
    traces:
      receivers:
        - otlp
      exporters:
        - debug
  telemetry:
    logs:
      level: "debug"
    metrics:
      level: detailed
      address: 0.0.0.0:8888
  extensions: [health_check]